language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
git:
  submodules: true
before_install:
  - sudo apt-get update
  - sudo apt-get install git build-essential libgtk-3-dev libsdl2-dev liblua5.3-dev zlib1g-dev